# Generated by Django 5.2.5 on 2025-08-13 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPSPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cpu_cores', models.IntegerField()),
                ('ram_gb', models.IntegerField()),
                ('storage_gb', models.IntegerField()),
                ('bandwidth_gb', models.IntegerField(help_text='Monthly bandwidth in GB')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contabo_image_id', models.CharField(help_text='Contabo image ID', max_length=100)),
                ('contabo_product_id', models.CharField(help_text='Contabo product ID', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('max_instances_per_user', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VPS Package',
                'verbose_name_plural': 'VPS Packages',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='VPSInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contabo_instance_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Creation'), ('creating', 'Being Created'), ('active', 'Active'), ('suspended', 'Suspended'), ('stopped', 'Stopped'), ('error', 'Error'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('root_password', models.CharField(help_text='Encrypted root password', max_length=255)),
                ('ssh_keys', models.TextField(blank=True, help_text='SSH public keys (JSON array)')),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_billing_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('auto_renewal', models.BooleanField(default=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_instances', to='accounts.userprofile')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.vpspackage')),
            ],
            options={
                'verbose_name': 'VPS Instance',
                'verbose_name_plural': 'VPS Instances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPSBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('auto', 'Automatic')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('size_gb', models.FloatField(default=0)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('contabo_backup_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('vps_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='vps.vpsinstance')),
            ],
            options={
                'verbose_name': 'VPS Backup',
                'verbose_name_plural': 'VPS Backups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPSAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('start', 'Start'), ('stop', 'Stop'), ('restart', 'Restart'), ('rebuild', 'Rebuild'), ('resize', 'Resize'), ('backup', 'Backup'), ('restore', 'Restore'), ('suspend', 'Suspend'), ('unsuspend', 'Unsuspend'), ('terminate', 'Terminate'), ('password_reset', 'Password Reset')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('contabo_task_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.userprofile')),
                ('vps_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='vps.vpsinstance')),
            ],
            options={
                'verbose_name': 'VPS Action',
                'verbose_name_plural': 'VPS Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPSUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage_percent', models.FloatField(default=0)),
                ('memory_usage_mb', models.IntegerField(default=0)),
                ('disk_usage_gb', models.FloatField(default=0)),
                ('bandwidth_used_gb', models.FloatField(default=0)),
                ('network_in_gb', models.FloatField(default=0)),
                ('network_out_gb', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('vps_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='vps.vpsinstance')),
            ],
            options={
                'verbose_name': 'VPS Usage Stats',
                'verbose_name_plural': 'VPS Usage Stats',
                'ordering': ['-recorded_at'],
                'unique_together': {('vps_instance', 'period_start')},
            },
        ),
    ]
